# Generated by Django 5.1 on 2024-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
