# Generated by Django 5.1 on 2024-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_customuser_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
