"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

os.environ["OPENAI_API_KEY"] = (
    "sk-proj-BkqMCfMCu8aJz0M19aj9T3BlbkFJCqFGN85AiM1NP2lJyrF1"
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-e18sp@zij0k3c=-b*2(gb56w$0%kpt_4xy7mze(=lwx!iu-ym2"
SUPABASE_URL="https://vchzcpsjnexzrzeqamix.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaHpjcHNqbmV4enJ6ZXFhbWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwODEzNjEsImV4cCI6MjA0NzY1NzM2MX0.kl5Lh8hphOTE-zDWNcdtFyeqnJ6yQLPm_jlYE-AQu2M"
STRIPE_API_KEY="sk_test_51Q2Ry600k5Gv8VrINcTYtnTWsvhH79RAbLostGPSKAyKN4VX7XW344LNOAZr2M0OfXkxroRXa6K8d0Or9RHOGTPz00Yw96jmwv"
STRIPE_WEBHOOK_LOCAL_KEY="whsec_a260af4d34359d4036690e3bcd93eb2d01e7ef732b7a7131e6a5b8f2b5710749"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = ["localhost", "rneuq-2604-3d09-1c77-8cb0-1801-dd6f-cb19-2e25.a.free.pinggy.link"]


# Application definition


INSTALLED_APPS = [
    "corsheaders",
    "backend",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4000",  # If you want to allow requests from your local environment
    "http://localhost:4100",
    "http://localhost:5000",
]

ROOT_URLCONF = "webapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "webapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# if os.getenv("ENV_DATABASE") == "PROD":
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.getenv("PROD_DB_NAME"),
#             "USER": os.getenv("PROD_DB_USER"),
#             "PASSWORD": os.getenv("PROD_DB_PASSWORD"),
#             "HOST": os.getenv("PROD_DB_HOST"),
#             "PORT": os.getenv("PROD_DB_PORT"),
#         }
#     }
# else:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.getenv("LOCAL_DB_NAME"),
#             "USER": os.getenv("LOCAL_DB_USER"),
#             "PASSWORD": os.getenv("LOCAL_DB_PASSWORD"),
#             "HOST": os.getenv("LOCAL_DB_HOST"),
#             "PORT": os.getenv("LOCAL_DB_PORT"),
#         }
#     }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "backend.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
